### ISSUE TITLE
Assembler messages: Fatal error: can't create lwip141/obj/echo.o: No such file or directory

### ISSUE THREAD

**Issue by Be997398715** [cjhonlyone/picorv32_Xilinx#2]
当使用windows cygwin环境下 安装了windows verilator和 windows risc-v-gcc7.7.1.exe，进入firmware时make firmware报错如下：
$ make firmware
/cygdrive/F/riscv_gnu_toolchain/windows_riscv/SysGCC/bin/riscv64-unknown-elf-gcc -c -march=rv32im -mabi=ilp32 -Wall -I./lwip141/lwip-1.4.1/src/include -I./lwip141/lwip-1.4.1/src/include/ipv4 -I./lwip141/contrib/ports/riscv/include/arch -I./lwip141/contrib/ports/riscv/include/netif -I./lwip141/contrib/ports/riscv/include -I./lwip141/contrib/apps/tcpecho_raw -Os -ffreestanding -nostdlib -o lwip141/obj/echo.o ./lwip141/contrib/apps/tcpecho_raw/echo.c
In file included from ./lwip141/lwip-1.4.1/src/include/lwip/arch.h:43:0,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/debug.h:35,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/opt.h:46,
                 from ./lwip141/contrib/apps/tcpecho_raw/echo.c:44:
./lwip141/contrib/ports/riscv/include/arch/cc.h:53:0: warning: "BYTE_ORDER" redefined
 #define BYTE_ORDER LITTLE_ENDIAN

In file included from f:\riscv_gnu_toolchain\windows_riscv\sysgcc\riscv64-unknown-elf\include\sys\types.h:67:0,
                 from f:\riscv_gnu_toolchain\windows_riscv\sysgcc\riscv64-unknown-elf\include\stdio.h:61,
                 from ./lwip141/contrib/ports/riscv/include/arch/cc.h:35,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/arch.h:43,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/debug.h:35,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/opt.h:46,
                 from ./lwip141/contrib/apps/tcpecho_raw/echo.c:44:
f:\riscv_gnu_toolchain\windows_riscv\sysgcc\riscv64-unknown-elf\include\machine\endian.h:20:0: note: this is the location of the previous definition
 #define BYTE_ORDER _BYTE_ORDER

In file included from ./lwip141/lwip-1.4.1/src/include/lwip/arch.h:43:0,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/debug.h:35,
                 from ./lwip141/lwip-1.4.1/src/include/lwip/opt.h:46,
                 from ./lwip141/contrib/apps/tcpecho_raw/echo.c:44:
./lwip141/contrib/ports/riscv/include/arch/cc.h:83:0: warning: "LWIP_PLATFORM_ASSERT" redefined
 #define LWIP_PLATFORM_ASSERT(x) printf(x)

./lwip141/contrib/ports/riscv/include/arch/cc.h:82:0: note: this is the location of the previous definition
 #define LWIP_PLATFORM_ASSERT

./lwip141/contrib/ports/riscv/include/arch/cc.h:87:0: warning: "LWIP_PLATFORM_DIAG" redefined
 #define LWIP_PLATFORM_DIAG(x) {printf x;}

./lwip141/contrib/ports/riscv/include/arch/cc.h:86:0: note: this is the location of the previous definition
 #define LWIP_PLATFORM_DIAG

Assembler messages:
Fatal error: can't create lwip141/obj/echo.o: No such file or directory
make: *** [Makefile:63：lwip141/obj/echo.o] 错误 1

**Comment by Be997398715** [comment]
solved

**Comment by joker1988** [comment]
> solved

这个问题怎么解决的？
